<div id='mostrarDivAñadirList' class='divEmergente'>";
	<div class='subDivEmergenteEliminarComentarios'>";
		<a href='#close' title='Close' class='close'>X</a>";
		<h3 class='ventanaModal'>Editar lista</h3>";
		<div class='formRespuesta'>";
			<form class='formListas' action='index.php?insertar=".$ins."' method='POST'>";
				<label>Nombre:</label>";
				<input class='formListas' type='text' name='añadirNombreList' placeholder='Titulo de la lista'>";
				<br><br>";
				<label>Descripción:</label>";
				<textarea class='formListas' rows='10' cols='70' name='añadirDescripcionList' placeholder='Descripción de la lista (opcional)'></textarea>";
				<br style='clear: both;'>";
				<input class='listas' type='submit' value='Enviar'>";
			</form>";
		</div>";
	</div>";
</div>";